# - name: install and run nginx
#   hosts: web
#   tasks:
#   - name: install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: present
#   - name: start nginx
#     ansible.builtin.systemd:
#       name: nginx
#       state: started
#       enabled: yes
#   - name: copy index.html
#     ansible.builtin.copy:
#       content: "<h1>Hello World</h1>"
#       dest: /usr/share/nginx/html/index.html
#   - name: restart nginx
#     ansible.builtin.systemd:
#       name: nginx
#       state: restarted
- name: install nginx and run it
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      
   

