- name: varible from files 
  hosts: localhost
  vars_promt:
    - name: Username
      promt: please enter your name
    - name: Password
      promt: please enter your password
      private: false
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi ,Username: {{Username}} and Password: {{Password"
