- name: check number 
  hosts: localhost
  vars_prompt:
    - name: number 
      prompt: please enter number
      private: no
  tasks:
    - name: number is less then 10
      ansible.builtin.debug:
        msg: "Given number {{number}} is less then 10"
      when: number <10
    - name: number is greater then 10
      ansible.builtin.debug:
        msg: "Given number {{number}} is greater then 10"
      when: number >10